project_id = "nqyyvqcmcyggvlcswkio"

[functions.send-preview-test]
verify_jwt = false

[functions.twilio-msg-status]
verify_jwt = false

[functions.maytapi-dispatcher]
verify_jwt = false

[functions.fb-ingest]
verify_jwt = false

[functions.fb-poll-fallback]
verify_jwt = false
