import { MarketingLayout } from '@/components/marketing/MarketingLayout';
import { Link } from 'react-router-dom';
import { TrendingUp, Globe, Lock, Layers, Cpu, Users, ArrowRight } from 'lucide-react';

const METRICS = [
  { v: '500M+', l: 'WhatsApp users in Africa' },
  { v: '$150B+', l: 'Global direct-sales market' },
  { v: '11', l: 'Active distributor groups on platform' },
  { v: '24/7', l: 'Autonomous prospecting uptime' },
];

const MOAT = [
  { icon: Cpu, t: 'AI Prospector trained on real distributor scripts', d: 'Not a generic chatbot. Every reply is grounded in an approved Knowledge Vault, intent-classified, safety-rail-passed, and audit-logged.' },
  { icon: Lock, t: 'Compliance-first architecture', d: 'Quiet hours, opt-outs, daily caps, atomic phone-locks, master kill switch. Designed to keep numbers warm and accounts unblocked.' },
  { icon: Layers, t: 'Multi-channel by design', d: 'Twilio + Maytapi + Facebook + Google Calendar + Drive — all unified. Most competitors lock you into one channel.' },
  { icon: Globe, t: 'African-market-native', d: 'Phone formats default to +27 ZA, SAST quiet hours, ZA province dictionary, Rand pricing, local Zoom schedules.' },
  { icon: Users, t: 'Built with an operator, not for one', d: 'Every feature ships from a real APLGO distributor running real campaigns — not a hypothetical persona.' },
  { icon: TrendingUp, t: 'Network effects', d: 'Each new distributor adds proven scripts, approved Knowledge Vault entries and benchmark intent data — improving the Prospector for everyone.' },
];

export default function Investors() {
  return (
    <MarketingLayout>
      <section className="gw-hero-grad py-20">
        <div className="max-w-5xl mx-auto px-4 lg:px-8 text-center">
          <div className="text-xs font-bold uppercase tracking-widest text-accent mb-3">Investor brief</div>
          <h1 className="text-4xl sm:text-5xl lg:text-6xl font-black tracking-tight">
            The operating system for <span className="gw-brand-grad-text">Africa's direct sellers.</span>
          </h1>
          <p className="mt-6 text-lg text-muted-foreground max-w-3xl mx-auto">
            500 million Africans use WhatsApp. Millions of them are distributors, wellness coaches, sales agents and small-business owners. GetWell Hub turns that activity into measurable, compliant, AI-driven revenue.
          </p>
        </div>
      </section>

      <section className="py-12">
        <div className="max-w-5xl mx-auto px-4 lg:px-8 grid grid-cols-2 md:grid-cols-4 gap-4">
          {METRICS.map((m) => (
            <div key={m.l} className="rounded-2xl border border-border bg-card p-6 text-center">
              <div className="text-3xl font-black gw-brand-grad-text">{m.v}</div>
              <div className="text-xs text-muted-foreground mt-1 uppercase tracking-wide">{m.l}</div>
            </div>
          ))}
        </div>
      </section>

      <section className="py-16">
        <div className="max-w-5xl mx-auto px-4 lg:px-8 grid lg:grid-cols-2 gap-12 items-start">
          <div>
            <div className="text-xs font-bold uppercase tracking-widest text-primary mb-2">The opportunity</div>
            <h2 className="text-3xl font-black mb-4">WhatsApp is how Africa sells. Nobody owns the workflow.</h2>
            <p className="text-muted-foreground leading-relaxed mb-3">
              Across the continent, direct sales — wellness, cosmetics, financial services, household goods — happen overwhelmingly on WhatsApp. Distributors juggle the WhatsApp app, a notebook, a Facebook tab and a memory of who said what.
            </p>
            <p className="text-muted-foreground leading-relaxed">
              GetWell Hub is the first WhatsApp-native CRM purpose-built for this market, with an autonomous AI Prospector that does the qualification, follow-up and onboarding work distributors physically cannot do at scale.
            </p>
          </div>
          <div>
            <div className="text-xs font-bold uppercase tracking-widest text-accent mb-2">The model</div>
            <h2 className="text-3xl font-black mb-4">SaaS per distributor team — usage-based on AI replies & broadcasts.</h2>
            <p className="text-muted-foreground leading-relaxed mb-3">
              Base subscription per workspace (Agent / Admin seats), metered AI prospector replies, group broadcast volume, and premium add-ons for advanced playbooks, Knowledge Vault size, and white-label deployment for upline MLM organisations.
            </p>
            <p className="text-muted-foreground leading-relaxed">
              Early traction is generated by an accredited APLGO distributor running daily live traffic — every product decision is validated against real conversion data, not pitch decks.
            </p>
          </div>
        </div>
      </section>

      <section className="py-16 bg-secondary/40 border-y border-border">
        <div className="max-w-6xl mx-auto px-4 lg:px-8">
          <div className="text-center mb-12">
            <div className="text-xs font-bold uppercase tracking-widest text-primary mb-2">The moat</div>
            <h2 className="text-3xl sm:text-4xl font-black tracking-tight">Why this isn't just another chatbot.</h2>
          </div>
          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-5">
            {MOAT.map((m) => (
              <div key={m.t} className="rounded-2xl border border-border bg-card p-6">
                <div className="w-11 h-11 rounded-xl gw-brand-grad-bg text-white flex items-center justify-center mb-4">
                  <m.icon size={20} />
                </div>
                <div className="font-bold text-base mb-1.5">{m.t}</div>
                <p className="text-sm text-muted-foreground leading-relaxed">{m.d}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section className="py-16">
        <div className="max-w-4xl mx-auto px-4 lg:px-8">
          <div className="rounded-3xl gw-brand-grad-bg text-white p-10 lg:p-14 text-center shadow-xl">
            <h3 className="text-3xl font-black mb-4">Talk to the founders.</h3>
            <p className="text-white/90 mb-6 max-w-xl mx-auto">
              We share a live demo on your number, the full Prospector audit log, and the unit economics behind every Facebook ad-to-partner conversion.
            </p>
            <a href="mailto:hello@getwellhub.dev" className="inline-flex items-center gap-2 px-6 py-3 rounded-lg bg-white text-primary font-bold hover:bg-white/90">
              hello@getwellhub.dev <ArrowRight size={16} />
            </a>
          </div>
          <div className="mt-8 text-center">
            <Link to="/prospector" className="text-sm font-semibold text-primary hover:underline">
              Or read the full Prospector flow →
            </Link>
          </div>
        </div>
      </section>
    </MarketingLayout>
  );
}
