// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/get-dispatch-policy.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.97.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var notAuthenticated = {
  content: [{ type: "text", text: "Not authenticated. Reconnect this MCP server and sign in." }],
  isError: true
};
var ALLOWED_GROUPS = [
  "APLGO",
  "APLGO | Health and Biz",
  "APLGO | Health and Biz KZN",
  "APLGO | Health and Biz Global Distributors",
  "APLGO | Health and Biz E&W Cape",
  "APLGO| Health and Biz North West",
  "APLGO 4 SHO",
  "Ascension Bloemfontein",
  "90 day Challenge and FB Campaign",
  "Botswana APLGO Presentations",
  "New Day New Life"
];
async function resolveOwnerId(supabase, ctx) {
  const { data: owners, error } = await supabase.from("profiles").select("id").eq("role", "super_admin");
  if (error) {
    const fallback = ctx.getUserId();
    if (fallback) return { ownerId: fallback };
    return { error: error.message };
  }
  if (!owners || owners.length === 0) return { error: "no_super_admin_found" };
  if (owners.length > 1) return { error: `multiple_super_admins_found (${owners.length})` };
  return { ownerId: owners[0].id };
}

// src/lib/mcp/tools/get-dispatch-policy.ts
var POLICY_KEYS = [
  "maytapi_daily_cap",
  "maytapi_outbound_frozen",
  "maytapi_freeze_until_at",
  "maytapi_min_inter_send_sec",
  "maytapi_hourly_cap",
  "maytapi_max_per_invocation"
];
var get_dispatch_policy_default = defineTool({
  name: "get_dispatch_policy",
  title: "Get WhatsApp dispatch policy",
  description: "Read the live WhatsApp group dispatch guardrails: cron interval, inter-send floor, hourly cap, daily cap, freeze state, the approved group list, standing rules and incident history.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("integration_settings").select("key, value").in("key", POLICY_KEYS);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const get = (key, fallback) => data?.find((s) => s.key === key)?.value ?? fallback;
    const policy = {
      cron_interval_minutes: 5,
      cron_job_name: "maytapi-send-group-poll",
      dispatch_guardrails: {
        min_inter_send_sec: Number(get("maytapi_min_inter_send_sec", "90")),
        hourly_cap: Number(get("maytapi_hourly_cap", "12")),
        max_per_invocation: Number(get("maytapi_max_per_invocation", "1"))
      },
      daily_cap: Number(get("maytapi_daily_cap", "56")),
      outbound_frozen: String(get("maytapi_outbound_frozen", "false")).toLowerCase() === "true",
      freeze_until: get("maytapi_freeze_until_at", null),
      approved_groups: ALLOWED_GROUPS,
      standing_rules: [
        "Dispatcher runs every 5 minutes (cron job: maytapi-send-group-poll).",
        "It processes at most 1 pending post per invocation.",
        "An 11-group wave therefore takes ~50-55 minutes to clear.",
        "Schedule the final wave to start 60-70 minutes before any time-sensitive event.",
        'Use event-time phrasing ("TONIGHT 7PM") rather than tight countdowns ("15 min left").',
        'Group posts MUST be inserted with status = "pending"; status = "queued" is ignored.'
      ],
      incident_history: [
        "2026-06-27: Burst-sending 11 groups in ~3 seconds triggered a WhatsApp 24-hour restriction.",
        "2026-07-23: Combined suite WhatsApp volume exceeded safe limits; suite-wide 24h freeze applied.",
        '2026-08-06: An 18:45 "15 minutes" wave landed at ~19:35 because of the 5-minute cron drift.',
        "2026-08-07: The pg_cron job hit HTTP 403 (stale key after rotation); only 1 group received the wave."
      ],
      self_discovery: {
        mcp_server: "This MCP server exposes every capability as a discoverable tool - no manual action names needed. Call get_dispatcher_health to diagnose stuck posts.",
        tools: [
          "get_dispatch_policy",
          "get_dispatcher_health",
          "get_maytapi_status",
          "set_maytapi_cap",
          "set_maytapi_freeze",
          "queue_group_post",
          "get_prospector_status",
          "list_contacts",
          "get_contact",
          "update_contact",
          "add_contact_note"
        ],
        legacy_bridge: {
          endpoint: "POST /functions/v1/mcp-bridge (shared-token, being retired)",
          discovery_action: '{"action":"list_actions"} returns the canonical action list',
          note: "Superseded by this OAuth MCP server. Prefer the tools above; the bridge remains only for legacy write actions (create_task, create_reminder, create_meeting, create_diary_entry)."
        }
      }
    };
    return {
      content: [{ type: "text", text: JSON.stringify(policy, null, 2) }],
      structuredContent: { policy }
    };
  }
});

// src/lib/mcp/tools/get-dispatcher-health.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
console.log("[build-stamp] mcp build=2026-08-13T14:35Z tools=23 includes=list_tasks,delete_meeting");
var HEALTH_KEYS = [
  "maytapi_outbound_frozen",
  "maytapi_freeze_until_at",
  "maytapi_freeze_reason",
  "maytapi_daily_cap"
];
var get_dispatcher_health_default = defineTool2({
  name: "get_dispatcher_health",
  title: "Get WhatsApp dispatcher health",
  description: "Self-diagnose the WhatsApp group dispatcher: last successful send, last failure and its reason, queue depth by status, sends in the last hour and last 24 hours against the caps, and whether outbound is frozen. Call this first when posts appear stuck.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    const supabase = supabaseForUser(ctx);
    const nowMs = Date.now();
    const hourAgo = new Date(nowMs - 60 * 60 * 1e3).toISOString();
    const dayAgo = new Date(nowMs - 24 * 60 * 60 * 1e3).toISOString();
    const { data: settings, error: sErr } = await supabase.from("integration_settings").select("key, value").in("key", HEALTH_KEYS);
    if (sErr) return { content: [{ type: "text", text: sErr.message }], isError: true };
    const get = (key, fallback) => settings?.find((s) => s.key === key)?.value ?? fallback;
    const { data: lastSent } = await supabase.from("scheduled_group_posts").select("id, target_group_name, scheduled_at, last_attempt_at, provider_message_id").eq("status", "sent").not("last_attempt_at", "is", null).order("last_attempt_at", { ascending: false }).limit(1).maybeSingle();
    const { data: lastFailure } = await supabase.from("scheduled_group_posts").select("id, target_group_name, scheduled_at, last_attempt_at, attempt_count, failure_reason").eq("status", "failed").order("last_attempt_at", { ascending: false }).limit(1).maybeSingle();
    const { data: queue, error: qErr } = await supabase.from("scheduled_group_posts").select("status, scheduled_at");
    if (qErr) return { content: [{ type: "text", text: qErr.message }], isError: true };
    const queue_by_status = {};
    let overdue_pending = 0;
    const nowIso = new Date(nowMs).toISOString();
    for (const row of queue ?? []) {
      queue_by_status[row.status] = (queue_by_status[row.status] ?? 0) + 1;
      if (row.status === "pending" && row.scheduled_at && row.scheduled_at < nowIso) overdue_pending += 1;
    }
    const { count: sentLastHour } = await supabase.from("scheduled_group_posts").select("id", { count: "exact", head: true }).eq("status", "sent").gte("last_attempt_at", hourAgo);
    const { count: sentLast24h } = await supabase.from("scheduled_group_posts").select("id", { count: "exact", head: true }).eq("status", "sent").gte("last_attempt_at", dayAgo);
    const { data: openStallAlerts } = await supabase.from("maytapi_delivery_alerts").select("id, target_group_name, failure_reason, created_at").eq("alert_status", "open").like("failure_reason", "dispatcher_%").order("created_at", { ascending: false }).limit(10);
    const lastTickMs = lastSent?.last_attempt_at ? Date.parse(lastSent.last_attempt_at) : null;
    const minutesSinceLastSend = lastTickMs ? Math.round((nowMs - lastTickMs) / 6e4) : null;
    const frozen = String(get("maytapi_outbound_frozen", "false")).toLowerCase() === "true";
    const freezeUntil = get("maytapi_freeze_until_at", null);
    const freezeActive = Boolean(freezeUntil && Date.parse(freezeUntil) > nowMs);
    let verdict;
    if (frozen || freezeActive) verdict = "paused: outbound is frozen";
    else if (overdue_pending === 0) verdict = "healthy: nothing overdue in the queue";
    else if (minutesSinceLastSend !== null && minutesSinceLastSend <= 15)
      verdict = "healthy: dispatcher ticked within the last 15 minutes";
    else
      verdict = "degraded: posts are overdue and no successful send in the last 15 minutes \u2014 likely a cron/auth failure on maytapi-send-group-poll";
    const health = {
      verdict,
      stall_alert: {
        watchdog_cron: "dispatcher-watchdog (every 15 minutes)",
        open_alerts: openStallAlerts?.length ?? 0,
        alerts: openStallAlerts ?? []
      },
      checked_at: nowIso,
      cron_job_name: "maytapi-send-group-poll",
      cron_interval_minutes: 5,
      last_successful_send: lastSent ?? null,
      minutes_since_last_successful_send: minutesSinceLastSend,
      last_failure: lastFailure ?? null,
      queue_by_status,
      overdue_pending,
      throughput: {
        sent_last_hour: sentLastHour ?? 0,
        hourly_cap: 12,
        sent_last_24h: sentLast24h ?? 0,
        daily_cap: Number(get("maytapi_daily_cap", "56"))
      },
      auth_status: {
        // The cron job posts {"trigger":"cron"} to maytapi-send-group, which bypasses
        // the bearer gate for approved queue rows. A 403 here historically meant a
        // stale hardcoded publishable key in the pg_cron job definition.
        mode: "cron trigger body bypass (no bearer required)",
        known_failure_mode: "HTTP 403 from maytapi-send-group after an API key rotation (stale key in the pg_cron job body).",
        healthy_signal: "a sent row with last_attempt_at inside the last 15 minutes"
      },
      outbound_frozen: frozen,
      freeze_until: freezeUntil,
      freeze_active: freezeActive,
      freeze_reason: get("maytapi_freeze_reason", null)
    };
    return {
      content: [{ type: "text", text: JSON.stringify(health, null, 2) }],
      structuredContent: { health }
    };
  }
});

// src/lib/mcp/tools/get-maytapi-status.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
var KEYS = ["maytapi_daily_cap", "maytapi_outbound_frozen", "reactivation_campaign_enabled"];
var get_maytapi_status_default = defineTool3({
  name: "get_maytapi_status",
  title: "Get WhatsApp sending status",
  description: "Current WhatsApp sending settings (daily cap, outbound freeze, reactivation campaign toggle) plus a count of scheduled group posts by status over the last 7 days.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    const supabase = supabaseForUser(ctx);
    const { data: settings, error: sErr } = await supabase.from("integration_settings").select("key, value").in("key", KEYS);
    if (sErr) return { content: [{ type: "text", text: sErr.message }], isError: true };
    const since = new Date(Date.now() - 7 * 24 * 60 * 60 * 1e3).toISOString();
    const { data: posts, error: pErr } = await supabase.from("scheduled_group_posts").select("status").gte("scheduled_at", since);
    if (pErr) return { content: [{ type: "text", text: pErr.message }], isError: true };
    const counts = {};
    for (const row of posts ?? []) counts[row.status] = (counts[row.status] ?? 0) + 1;
    const settingsMap = {};
    for (const k of KEYS) settingsMap[k] = settings?.find((s) => s.key === k)?.value ?? null;
    const result = { settings: settingsMap, group_posts_last_7_days: counts };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/set-maytapi-cap.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";
var set_maytapi_cap_default = defineTool4({
  name: "set_maytapi_cap",
  title: "Set WhatsApp daily cap",
  description: "Set the maximum number of WhatsApp messages the dispatcher may send in a 24-hour period. Requires an admin account.",
  inputSchema: { cap: z.number().int().positive().max(200).describe("New daily cap.") },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ cap }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    const supabase = supabaseForUser(ctx);
    const { error } = await supabase.from("integration_settings").upsert({ key: "maytapi_daily_cap", value: String(cap) }, { onConflict: "key" });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `maytapi_daily_cap set to ${cap}` }],
      structuredContent: { maytapi_daily_cap: cap }
    };
  }
});

// src/lib/mcp/tools/set-maytapi-freeze.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var set_maytapi_freeze_default = defineTool5({
  name: "set_maytapi_freeze",
  title: "Freeze or unfreeze WhatsApp outbound",
  description: "Freeze (true) or resume (false) all outbound WhatsApp sending. Freezing halts every group and 1-on-1 dispatch immediately. Requires an admin account.",
  inputSchema: { frozen: z2.boolean().describe("true to freeze outbound sending, false to resume.") },
  annotations: { readOnlyHint: false, destructiveHint: true, openWorldHint: false },
  handler: async ({ frozen }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    const supabase = supabaseForUser(ctx);
    const { error } = await supabase.from("integration_settings").upsert({ key: "maytapi_outbound_frozen", value: String(frozen) }, { onConflict: "key" });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `maytapi_outbound_frozen set to ${frozen}` }],
      structuredContent: { maytapi_outbound_frozen: frozen }
    };
  }
});

// src/lib/mcp/tools/queue-group-post.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var queue_group_post_default = defineTool6({
  name: "queue_group_post",
  title: "Queue a WhatsApp group post",
  description: "Schedule one message to one of the 11 approved WhatsApp groups. The post is inserted with status 'pending' so the dispatcher picks it up. Remember: 1 group per 5-minute tick, so an 11-group wave takes ~55 minutes to clear.",
  inputSchema: {
    group_name: z3.string().min(1).describe("Exact name of an approved WhatsApp group."),
    message_content: z3.string().min(1).describe("Message body to post."),
    scheduled_at: z3.string().min(1).describe("ISO 8601 timestamp for when the post should go out."),
    image_url: z3.string().url().optional().describe("Optional image to attach.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ group_name, message_content, scheduled_at, image_url }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    if (!ALLOWED_GROUPS.includes(group_name)) {
      return {
        content: [{ type: "text", text: `"${group_name}" is not an approved group. Allowed: ${ALLOWED_GROUPS.join(", ")}` }],
        isError: true
      };
    }
    if (Number.isNaN(Date.parse(scheduled_at))) {
      return { content: [{ type: "text", text: "scheduled_at must be an ISO timestamp" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data: group, error: gErr } = await supabase.from("whatsapp_groups").select("group_jid, user_id").eq("group_name", group_name).eq("is_active", true).limit(1).maybeSingle();
    if (gErr) return { content: [{ type: "text", text: gErr.message }], isError: true };
    if (!group) return { content: [{ type: "text", text: `Group not found or inactive: ${group_name}` }], isError: true };
    const { data: inserted, error } = await supabase.from("scheduled_group_posts").insert({
      user_id: group.user_id,
      target_group_name: group_name,
      target_group_jid: group.group_jid,
      message_content,
      image_url: image_url ?? null,
      scheduled_at: new Date(scheduled_at).toISOString(),
      status: "pending",
      source: "mcp"
    }).select("id, target_group_name, scheduled_at, status").single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(inserted) }],
      structuredContent: { post: inserted }
    };
  }
});

// src/lib/mcp/tools/get-prospector-status.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.26.1";
var get_prospector_status_default = defineTool7({
  name: "get_prospector_status",
  title: "Get prospector cadence status",
  description: "Counts of prospect cadence states by status, plus the next 20 upcoming scheduled sends.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    const supabase = supabaseForUser(ctx);
    const { data: states, error: cErr } = await supabase.from("prospect_cadence_state").select("status");
    if (cErr) return { content: [{ type: "text", text: cErr.message }], isError: true };
    const counts = {};
    for (const row of states ?? []) counts[row.status] = (counts[row.status] ?? 0) + 1;
    const { data: upcoming, error: uErr } = await supabase.from("prospect_cadence_state").select("id, contact_id, sequence_key, current_step, next_send_at, last_sent_at").eq("status", "active").not("next_send_at", "is", null).order("next_send_at", { ascending: true }).limit(20);
    if (uErr) return { content: [{ type: "text", text: uErr.message }], isError: true };
    const result = { counts_by_status: counts, upcoming_sends: upcoming ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/list-contacts.ts
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var list_contacts_default = defineTool8({
  name: "list_contacts",
  title: "List contacts",
  description: "List CRM contacts visible to the signed-in user, newest first. Optional filters by lead type, temperature, tag or free-text search on name/phone.",
  inputSchema: {
    lead_type: z4.string().optional().describe("Filter by lead type."),
    temperature: z4.string().optional().describe("Filter by temperature (hot/warm/cold)."),
    tag: z4.string().optional().describe("Filter by a single tag."),
    search: z4.string().optional().describe("Free-text match on name or phone."),
    limit: z4.number().int().min(1).max(100).optional().describe("Max rows (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ lead_type, temperature, tag, search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("contacts").select("id, name, phone_normalized, email, lead_type, temperature, tags, notes, do_not_contact, updated_at").eq("is_deleted", false).order("updated_at", { ascending: false }).limit(limit ?? 25);
    if (lead_type) query = query.eq("lead_type", lead_type);
    if (temperature) query = query.eq("temperature", temperature);
    if (tag) query = query.contains("tags", [tag]);
    if (search) query = query.or(`name.ilike.%${search}%,phone_normalized.ilike.%${search}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify({ count: data?.length ?? 0, contacts: data ?? [] }, null, 2) }],
      structuredContent: { count: data?.length ?? 0, contacts: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-contact.ts
import { defineTool as defineTool9 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^3.25.76";
var get_contact_default = defineTool9({
  name: "get_contact",
  title: "Get a contact",
  description: "Fetch one contact by id or normalized phone number, together with its 10 most recent activity records.",
  inputSchema: {
    contact_id: z5.string().uuid().optional().describe("Contact UUID."),
    phone_normalized: z5.string().optional().describe("Phone in +E164 format.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ contact_id, phone_normalized }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    if (!contact_id && !phone_normalized) {
      return { content: [{ type: "text", text: "Provide contact_id or phone_normalized" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("contacts").select("*").eq("is_deleted", false).limit(1);
    query = contact_id ? query.eq("id", contact_id) : query.eq("phone_normalized", phone_normalized);
    const { data: contact, error } = await query.maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!contact) return { content: [{ type: "text", text: "Contact not found" }], isError: true };
    const { data: recentActivity } = await supabase.from("contact_activity").select("type, metadata, created_at").eq("contact_id", contact.id).order("created_at", { ascending: false }).limit(10);
    const result = { contact, recent_activity: recentActivity ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/update-contact.ts
import { defineTool as defineTool10 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z6 } from "npm:zod@^3.25.76";
var update_contact_default = defineTool10({
  name: "update_contact",
  title: "Update a contact",
  description: "Update editable fields on a contact: name, email, lead type, temperature, tags, or the do-not-contact flag. Phone numbers are never changed here.",
  inputSchema: {
    contact_id: z6.string().uuid().describe("Contact UUID."),
    name: z6.string().optional(),
    email: z6.string().email().nullable().optional(),
    lead_type: z6.enum(["prospect", "registered", "buyer", "vip"]).optional(),
    temperature: z6.enum(["hot", "warm", "cold"]).optional(),
    tags: z6.array(z6.string()).optional(),
    do_not_contact: z6.boolean().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    const { contact_id, ...fields } = input;
    const updates = { updated_at: (/* @__PURE__ */ new Date()).toISOString() };
    for (const [key, value] of Object.entries(fields)) {
      if (value !== void 0) updates[key] = value;
    }
    if (Object.keys(updates).length === 1) {
      return { content: [{ type: "text", text: "No updatable fields provided" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("contacts").update(updates).eq("id", contact_id).eq("is_deleted", false).select("id, name, phone_normalized, email, lead_type, temperature, tags, do_not_contact, updated_at").single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { contact: data }
    };
  }
});

// src/lib/mcp/tools/add-contact-note.ts
import { defineTool as defineTool11 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z7 } from "npm:zod@^3.25.76";
var add_contact_note_default = defineTool11({
  name: "add_contact_note",
  title: "Add a note to a contact",
  description: "Append a timestamped note to a contact's notes field and record it on the contact activity trail.",
  inputSchema: {
    contact_id: z7.string().uuid().describe("Contact UUID."),
    note: z7.string().min(1).describe("Note text to append.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ contact_id, note }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    const supabase = supabaseForUser(ctx);
    const { data: existing, error: fetchErr } = await supabase.from("contacts").select("notes").eq("id", contact_id).eq("is_deleted", false).maybeSingle();
    if (fetchErr) return { content: [{ type: "text", text: fetchErr.message }], isError: true };
    if (!existing) return { content: [{ type: "text", text: "Contact not found" }], isError: true };
    const stamp = (/* @__PURE__ */ new Date()).toISOString().slice(0, 16).replace("T", " ");
    const appended = existing.notes ? `${existing.notes}

[${stamp} \xB7 via MCP] ${note}` : `[${stamp} \xB7 via MCP] ${note}`;
    const { data: updated, error: updateErr } = await supabase.from("contacts").update({ notes: appended, updated_at: (/* @__PURE__ */ new Date()).toISOString() }).eq("id", contact_id).select("id, notes").single();
    if (updateErr) return { content: [{ type: "text", text: updateErr.message }], isError: true };
    await supabase.from("contact_activity").insert({
      contact_id,
      type: "note_added",
      performed_by: ctx.getUserId(),
      metadata: { source: "mcp", note_preview: note.slice(0, 160) }
    });
    return {
      content: [{ type: "text", text: updated.notes ?? "" }],
      structuredContent: { contact_id, notes: updated.notes }
    };
  }
});

// src/lib/mcp/tools/create-plan-task.ts
import { defineTool as defineTool12 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z8 } from "npm:zod@^3.25.76";
var create_plan_task_default = defineTool12({
  name: "create_plan_task",
  title: "Create a plan task",
  description: "Create a task on the Plan board. Skips creation and returns the existing row when an open task with the same title already exists.",
  inputSchema: {
    title: z8.string().min(1).describe("Task title."),
    priority: z8.enum(["low", "medium", "high", "urgent"]).optional().describe("Task priority (default 'medium').")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ title, priority }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    const supabase = supabaseForUser(ctx);
    const owner = await resolveOwnerId(supabase, ctx);
    if ("error" in owner) return { content: [{ type: "text", text: owner.error }], isError: true };
    const { data: existing, error: dupErr } = await supabase.from("plan_tasks").select("id, title, priority, status").eq("user_id", owner.ownerId).eq("title", title).neq("status", "done").limit(1);
    if (dupErr) return { content: [{ type: "text", text: dupErr.message }], isError: true };
    if (existing && existing.length > 0) {
      return {
        content: [{ type: "text", text: JSON.stringify({ ...existing[0], deduped: true }) }],
        structuredContent: { task: existing[0], deduped: true }
      };
    }
    const { data, error } = await supabase.from("plan_tasks").insert({ title, priority: priority ?? "medium", user_id: owner.ownerId }).select("id, title, priority, status").single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { task: data, deduped: false }
    };
  }
});

// src/lib/mcp/tools/create-plan-meeting.ts
import { defineTool as defineTool13 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z9 } from "npm:zod@^3.25.76";
var create_plan_meeting_default = defineTool13({
  name: "create_plan_meeting",
  title: "Create a plan meeting",
  description: "Schedule a meeting on the Plan calendar.",
  inputSchema: {
    title: z9.string().min(1).describe("Meeting title."),
    start_time: z9.string().min(1).describe("ISO 8601 start datetime."),
    location: z9.string().nullish().describe("Optional location.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ title, start_time, location }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    if (Number.isNaN(Date.parse(start_time))) {
      return { content: [{ type: "text", text: "start_time must be an ISO 8601 datetime" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const owner = await resolveOwnerId(supabase, ctx);
    if ("error" in owner) return { content: [{ type: "text", text: owner.error }], isError: true };
    const { data, error } = await supabase.from("plan_meetings").insert({
      title,
      start_time: new Date(start_time).toISOString(),
      location: location ?? null,
      user_id: owner.ownerId
    }).select("id, title, start_time, location").single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { meeting: data }
    };
  }
});

// src/lib/mcp/tools/create-plan-reminder.ts
import { defineTool as defineTool14 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z10 } from "npm:zod@^3.25.76";
var create_plan_reminder_default = defineTool14({
  name: "create_plan_reminder",
  title: "Create a plan reminder",
  description: "Create a reminder on the Plan board (the 'Remind me to\u2026' text goes in title).",
  inputSchema: {
    title: z10.string().min(1).describe("Reminder text."),
    reminder_time: z10.string().min(1).describe("ISO 8601 datetime for the reminder.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ title, reminder_time }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    if (Number.isNaN(Date.parse(reminder_time))) {
      return { content: [{ type: "text", text: "reminder_time must be an ISO 8601 datetime" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const owner = await resolveOwnerId(supabase, ctx);
    if ("error" in owner) return { content: [{ type: "text", text: owner.error }], isError: true };
    const { data, error } = await supabase.from("plan_reminders").insert({
      title,
      reminder_time: new Date(reminder_time).toISOString(),
      user_id: owner.ownerId
    }).select("id, title, reminder_time").single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { reminder: data }
    };
  }
});

// src/lib/mcp/tools/send-whatsapp-message.ts
import { defineTool as defineTool15 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z11 } from "npm:zod@^3.25.76";
var DAY_MS = 24 * 60 * 60 * 1e3;
function err(text, extra) {
  return {
    content: [{ type: "text", text }],
    structuredContent: { sent: false, ...extra ?? {} },
    isError: true
  };
}
var send_whatsapp_message_default = defineTool15({
  name: "send_whatsapp_message",
  title: "Send a 1:1 WhatsApp message",
  description: "Send a real one-to-one WhatsApp message to a single contact via the existing Maytapi integration (NOT a group post). Refuses if the contact is marked do_not_contact, if outbound is frozen, if the shared daily send cap is reached, or if the contact's last inbound message is older than 24 hours (WhatsApp customer service window \u2014 a pre-approved template must be used instead). On success the send is logged to the contact activity timeline and the contact's last_outbound_at / last_outbound_provider are updated.",
  inputSchema: {
    contact_id: z11.string().uuid().optional().describe("Contact UUID. Provide this or phone_normalized."),
    phone_normalized: z11.string().optional().describe("Phone in +E164 format. Provide this or contact_id."),
    message_body: z11.string().min(1).max(4e3).describe("The exact final text to send. No templating is applied.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
  handler: async ({ contact_id, phone_normalized, message_body }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    if (!contact_id && !phone_normalized) {
      return err("Provide contact_id or phone_normalized.");
    }
    const supabase = supabaseForUser(ctx);
    const now = Date.now();
    let cq = supabase.from("contacts").select("id, name, phone_normalized, do_not_contact, do_not_contact_reason").eq("is_deleted", false).limit(1);
    cq = contact_id ? cq.eq("id", contact_id) : cq.eq("phone_normalized", phone_normalized);
    const { data: contact, error: cErr } = await cq.maybeSingle();
    if (cErr) return err(cErr.message);
    if (!contact) return err("Contact not found.");
    if (!contact.phone_normalized) return err("Contact has no normalized phone number; cannot send.");
    if (contact.do_not_contact) {
      return err(
        `Refused: contact ${contact.name ?? contact.id} is marked do_not_contact` + (contact.do_not_contact_reason ? ` (${contact.do_not_contact_reason})` : "") + ". No message was sent.",
        { reason: "do_not_contact", contact_id: contact.id }
      );
    }
    const { data: settingRows } = await supabase.from("integration_settings").select("key, value").in("key", ["maytapi_outbound_frozen", "maytapi_freeze_until_at", "maytapi_freeze_reason", "maytapi_daily_cap"]);
    const get = (k, fallback = null) => settingRows?.find((s) => s.key === k)?.value ?? fallback;
    const frozenFlag = String(get("maytapi_outbound_frozen", "false")).trim().toLowerCase() === "true";
    const freezeUntil = get("maytapi_freeze_until_at");
    const freezeActive = frozenFlag && (!freezeUntil || Date.parse(freezeUntil) > now);
    if (freezeActive) {
      return err(
        `Refused: WhatsApp outbound is frozen${freezeUntil ? ` until ${freezeUntil}` : ""}${get("maytapi_freeze_reason") ? ` (${get("maytapi_freeze_reason")})` : ""}. No message was sent.`,
        { reason: "outbound_frozen", freeze_until: freezeUntil }
      );
    }
    const dailyCap = Number(get("maytapi_daily_cap", "56"));
    const since24h = new Date(now - DAY_MS).toISOString();
    const { count: groupSent } = await supabase.from("scheduled_group_posts").select("id", { count: "exact", head: true }).in("status", ["sent", "delivered"]).gte("last_attempt_at", since24h);
    const { count: directSent } = await supabase.from("contact_activity").select("id", { count: "exact", head: true }).eq("type", "maytapi_message").filter("metadata->>direction", "eq", "outbound").gte("created_at", since24h);
    const usedToday = (groupSent ?? 0) + (directSent ?? 0);
    if (Number.isFinite(dailyCap) && usedToday >= dailyCap) {
      return err(
        `Refused: shared Maytapi daily cap reached (${usedToday}/${dailyCap} in the last 24h). No message was sent.`,
        { reason: "daily_cap_reached", used_last_24h: usedToday, daily_cap: dailyCap }
      );
    }
    const { data: lastInboundActivity } = await supabase.from("contact_activity").select("created_at").eq("contact_id", contact.id).eq("type", "maytapi_message").filter("metadata->>direction", "eq", "inbound").order("created_at", { ascending: false }).limit(1).maybeSingle();
    const { data: conversations } = await supabase.from("conversations").select("id").eq("contact_id", contact.id);
    let lastInboundMessage = null;
    const convIds = (conversations ?? []).map((c) => c.id);
    if (convIds.length) {
      const { data: msg } = await supabase.from("messages").select("created_at").in("conversation_id", convIds).eq("direction", "inbound").order("created_at", { ascending: false }).limit(1).maybeSingle();
      lastInboundMessage = msg?.created_at ?? null;
    }
    const candidates = [lastInboundActivity?.created_at ?? null, lastInboundMessage].filter((v) => !!v).map((v) => Date.parse(v)).filter((v) => !Number.isNaN(v));
    const lastInboundAt = candidates.length ? Math.max(...candidates) : null;
    if (lastInboundAt === null || now - lastInboundAt > DAY_MS) {
      const hours = lastInboundAt === null ? null : Math.round((now - lastInboundAt) / 36e5);
      return err(
        "Refused: outside WhatsApp's 24-hour customer service window. " + (lastInboundAt === null ? "This contact has never sent an inbound message." : `Last inbound message was ${hours} hours ago (${new Date(lastInboundAt).toISOString()}).`) + " Free-form sending outside the window risks the business number being restricted by Meta \u2014 use a pre-approved template instead. No message was sent.",
        {
          reason: "outside_24h_window",
          last_inbound_at: lastInboundAt ? new Date(lastInboundAt).toISOString() : null,
          contact_id: contact.id
        }
      );
    }
    const { data: sendResult, error: fnErr } = await supabase.functions.invoke("maytapi-send-direct", {
      body: {
        to_number: contact.phone_normalized,
        message: message_body,
        contact_id: contact.id,
        source: "mcp_send_whatsapp_message"
      }
    });
    if (fnErr) {
      return err(`Maytapi send failed: ${fnErr.message}`, { reason: "maytapi_error", details: sendResult ?? null });
    }
    if (!sendResult?.success) {
      return err(
        `Maytapi send failed: ${sendResult?.error ?? sendResult?.reason ?? "unknown provider error"}`,
        { reason: sendResult?.reason ?? "maytapi_error", details: sendResult ?? null }
      );
    }
    const providerMessageId = sendResult?.message_id ?? null;
    const sentAt = (/* @__PURE__ */ new Date()).toISOString();
    await supabase.from("contact_activity").insert({
      contact_id: contact.id,
      type: "maytapi_message",
      performed_by: ctx.getUserId() ?? null,
      metadata: {
        direction: "outbound",
        maytapi_message_id: providerMessageId,
        phone_last4: contact.phone_normalized.slice(-4),
        msg_type: "text",
        body_preview: message_body.slice(0, 140),
        body: message_body,
        source: "mcp_send_whatsapp_message",
        sent_at: sentAt
      }
    });
    await supabase.from("contacts").update({ last_outbound_at: sentAt, last_outbound_provider: "maytapi" }).eq("id", contact.id);
    const result = {
      sent: true,
      contact_id: contact.id,
      to: contact.phone_normalized,
      provider: "maytapi",
      provider_message_id: providerMessageId,
      sent_at: sentAt,
      window: "within_24h_session",
      daily_cap: { used_last_24h: usedToday + 1, cap: dailyCap }
    };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/list-plan-tasks.ts
import { defineTool as defineTool16 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z12 } from "npm:zod@^3.25.76";
var list_plan_tasks_default = defineTool16({
  name: "list_tasks",
  title: "List plan tasks",
  description: "Read tasks from the Plan board, optionally filtered by status ('pending'/'in_progress'/'done') and/or a single calendar day (matches due_date). Read-only.",
  inputSchema: {
    status: z12.string().optional().describe("Filter by status, e.g. 'pending'."),
    date: z12.string().optional().describe("YYYY-MM-DD \u2014 filters to tasks due on this day."),
    limit: z12.number().int().min(1).max(100).optional().describe("Max rows (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, date, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    const supabase = supabaseForUser(ctx);
    const owner = await resolveOwnerId(supabase, ctx);
    if ("error" in owner) return { content: [{ type: "text", text: owner.error }], isError: true };
    let query = supabase.from("plan_tasks").select("id, title, description, status, priority, due_date, start_date, completed_at, source, created_at").eq("user_id", owner.ownerId).order("due_date", { ascending: true, nullsFirst: false }).limit(limit ?? 50);
    if (status) query = query.eq("status", status);
    if (date) {
      if (!/^\d{4}-\d{2}-\d{2}$/.test(date)) {
        return { content: [{ type: "text", text: "date must be YYYY-MM-DD" }], isError: true };
      }
      query = query.gte("due_date", `${date}T00:00:00.000Z`).lte("due_date", `${date}T23:59:59.999Z`);
    }
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const result = { tasks: data ?? [], count: data?.length ?? 0 };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/complete-plan-task.ts
import { defineTool as defineTool17 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z13 } from "npm:zod@^3.25.76";
var complete_plan_task_default = defineTool17({
  name: "complete_task",
  title: "Mark a plan task done",
  description: "Mark a Plan board task as done (sets status to 'done' and stamps completed_at). Use list_tasks first to find the task id.",
  inputSchema: {
    id: z13.string().uuid().describe("plan_tasks.id \u2014 required.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    const supabase = supabaseForUser(ctx);
    const owner = await resolveOwnerId(supabase, ctx);
    if ("error" in owner) return { content: [{ type: "text", text: owner.error }], isError: true };
    const { data: existing, error: fetchErr } = await supabase.from("plan_tasks").select("id").eq("id", id).eq("user_id", owner.ownerId).maybeSingle();
    if (fetchErr) return { content: [{ type: "text", text: fetchErr.message }], isError: true };
    if (!existing) return { content: [{ type: "text", text: "Task not found" }], isError: true };
    const { data, error } = await supabase.from("plan_tasks").update({ status: "done", completed_at: (/* @__PURE__ */ new Date()).toISOString() }).eq("id", id).select("id, title, status, completed_at").single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { task: data }
    };
  }
});

// src/lib/mcp/tools/delete-plan-task.ts
import { defineTool as defineTool18 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z14 } from "npm:zod@^3.25.76";
var delete_plan_task_default = defineTool18({
  name: "delete_task",
  title: "Delete a plan task",
  description: "Permanently delete a task from the Plan board. This is a hard delete \u2014 there is no undo. Use list_tasks first to find the task id.",
  inputSchema: {
    id: z14.string().uuid().describe("plan_tasks.id \u2014 required.")
  },
  annotations: { readOnlyHint: false, destructiveHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    const supabase = supabaseForUser(ctx);
    const owner = await resolveOwnerId(supabase, ctx);
    if ("error" in owner) return { content: [{ type: "text", text: owner.error }], isError: true };
    const { data: existing, error: fetchErr } = await supabase.from("plan_tasks").select("id").eq("id", id).eq("user_id", owner.ownerId).maybeSingle();
    if (fetchErr) return { content: [{ type: "text", text: fetchErr.message }], isError: true };
    if (!existing) return { content: [{ type: "text", text: "Task not found" }], isError: true };
    const { error } = await supabase.from("plan_tasks").delete().eq("id", id);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify({ deleted_id: id }) }],
      structuredContent: { deleted_id: id }
    };
  }
});

// src/lib/mcp/tools/list-plan-reminders.ts
import { defineTool as defineTool19 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z15 } from "npm:zod@^3.25.76";
var list_plan_reminders_default = defineTool19({
  name: "list_reminders",
  title: "List plan reminders",
  description: "Read reminders from the Plan board, optionally filtered by is_done and/or a single calendar day (matches reminder_time). Read-only.",
  inputSchema: {
    is_done: z15.boolean().optional(),
    date: z15.string().optional().describe("YYYY-MM-DD \u2014 filters to reminders on this day."),
    limit: z15.number().int().min(1).max(100).optional().describe("Max rows (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ is_done, date, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    const supabase = supabaseForUser(ctx);
    const owner = await resolveOwnerId(supabase, ctx);
    if ("error" in owner) return { content: [{ type: "text", text: owner.error }], isError: true };
    let query = supabase.from("plan_reminders").select("id, title, description, reminder_time, is_done, created_at").eq("user_id", owner.ownerId).order("reminder_time", { ascending: true }).limit(limit ?? 50);
    if (typeof is_done === "boolean") query = query.eq("is_done", is_done);
    if (date) {
      if (!/^\d{4}-\d{2}-\d{2}$/.test(date)) {
        return { content: [{ type: "text", text: "date must be YYYY-MM-DD" }], isError: true };
      }
      query = query.gte("reminder_time", `${date}T00:00:00.000Z`).lte("reminder_time", `${date}T23:59:59.999Z`);
    }
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const result = { reminders: data ?? [], count: data?.length ?? 0 };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/complete-plan-reminder.ts
import { defineTool as defineTool20 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z16 } from "npm:zod@^3.25.76";
var complete_plan_reminder_default = defineTool20({
  name: "complete_reminder",
  title: "Mark a plan reminder done",
  description: "Mark a Plan board reminder as done (sets is_done to true). Use list_reminders first to find the reminder id.",
  inputSchema: {
    id: z16.string().uuid().describe("plan_reminders.id \u2014 required.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    const supabase = supabaseForUser(ctx);
    const owner = await resolveOwnerId(supabase, ctx);
    if ("error" in owner) return { content: [{ type: "text", text: owner.error }], isError: true };
    const { data: existing, error: fetchErr } = await supabase.from("plan_reminders").select("id").eq("id", id).eq("user_id", owner.ownerId).maybeSingle();
    if (fetchErr) return { content: [{ type: "text", text: fetchErr.message }], isError: true };
    if (!existing) return { content: [{ type: "text", text: "Reminder not found" }], isError: true };
    const { data, error } = await supabase.from("plan_reminders").update({ is_done: true }).eq("id", id).select("id, title, is_done").single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { reminder: data }
    };
  }
});

// src/lib/mcp/tools/delete-plan-reminder.ts
import { defineTool as defineTool21 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z17 } from "npm:zod@^3.25.76";
var delete_plan_reminder_default = defineTool21({
  name: "delete_reminder",
  title: "Delete a plan reminder",
  description: "Permanently delete a reminder from the Plan board. This is a hard delete \u2014 there is no undo. Use list_reminders first to find the reminder id.",
  inputSchema: {
    id: z17.string().uuid().describe("plan_reminders.id \u2014 required.")
  },
  annotations: { readOnlyHint: false, destructiveHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    const supabase = supabaseForUser(ctx);
    const owner = await resolveOwnerId(supabase, ctx);
    if ("error" in owner) return { content: [{ type: "text", text: owner.error }], isError: true };
    const { data: existing, error: fetchErr } = await supabase.from("plan_reminders").select("id").eq("id", id).eq("user_id", owner.ownerId).maybeSingle();
    if (fetchErr) return { content: [{ type: "text", text: fetchErr.message }], isError: true };
    if (!existing) return { content: [{ type: "text", text: "Reminder not found" }], isError: true };
    const { error } = await supabase.from("plan_reminders").delete().eq("id", id);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify({ deleted_id: id }) }],
      structuredContent: { deleted_id: id }
    };
  }
});

// src/lib/mcp/tools/list-plan-meetings.ts
import { defineTool as defineTool22 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z18 } from "npm:zod@^3.25.76";
var list_plan_meetings_default = defineTool22({
  name: "list_meetings",
  title: "List plan meetings",
  description: "Read meetings from the Plan calendar, optionally filtered to a single calendar day (matches start_time). Read-only.",
  inputSchema: {
    date: z18.string().optional().describe("YYYY-MM-DD \u2014 filters to meetings on this day."),
    limit: z18.number().int().min(1).max(100).optional().describe("Max rows (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ date, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    const supabase = supabaseForUser(ctx);
    const owner = await resolveOwnerId(supabase, ctx);
    if ("error" in owner) return { content: [{ type: "text", text: owner.error }], isError: true };
    let query = supabase.from("plan_meetings").select("id, title, start_time, location, created_at").eq("user_id", owner.ownerId).order("start_time", { ascending: true }).limit(limit ?? 50);
    if (date) {
      if (!/^\d{4}-\d{2}-\d{2}$/.test(date)) {
        return { content: [{ type: "text", text: "date must be YYYY-MM-DD" }], isError: true };
      }
      query = query.gte("start_time", `${date}T00:00:00.000Z`).lte("start_time", `${date}T23:59:59.999Z`);
    }
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const result = { meetings: data ?? [], count: data?.length ?? 0 };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/delete-plan-meeting.ts
import { defineTool as defineTool23 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z19 } from "npm:zod@^3.25.76";
var delete_plan_meeting_default = defineTool23({
  name: "delete_meeting",
  title: "Delete a plan meeting",
  description: "Permanently delete a meeting from the Plan calendar. This is a hard delete \u2014 there is no undo. Use list_meetings first to find the meeting id.",
  inputSchema: {
    id: z19.string().uuid().describe("plan_meetings.id \u2014 required.")
  },
  annotations: { readOnlyHint: false, destructiveHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    const supabase = supabaseForUser(ctx);
    const owner = await resolveOwnerId(supabase, ctx);
    if ("error" in owner) return { content: [{ type: "text", text: owner.error }], isError: true };
    const { data: existing, error: fetchErr } = await supabase.from("plan_meetings").select("id").eq("id", id).eq("user_id", owner.ownerId).maybeSingle();
    if (fetchErr) return { content: [{ type: "text", text: fetchErr.message }], isError: true };
    if (!existing) return { content: [{ type: "text", text: "Meeting not found" }], isError: true };
    const { error } = await supabase.from("plan_meetings").delete().eq("id", id);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify({ deleted_id: id }) }],
      structuredContent: { deleted_id: id }
    };
  }
});

// src/lib/mcp/tools/list-conversations.ts
import { defineTool as defineTool24 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z20 } from "npm:zod@^3.25.76";
var list_conversations_default = defineTool24({
  name: "list_conversations",
  title: "List inbox conversations",
  description: "List recent conversations from the unified inbox (Twilio SMS/WhatsApp + Maytapi WhatsApp), newest first. Optionally filter to a single channel or to unread conversations only.",
  inputSchema: {
    provider: z20.enum(["twilio", "maytapi", "all"]).optional().describe("Filter to conversations with at least one message on this channel (default 'all')."),
    unread_only: z20.boolean().optional().describe("Only return conversations with unread_count > 0."),
    limit: z20.number().int().min(1).max(100).optional().describe("Max rows (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ provider, unread_only, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    const supabase = supabaseForUser(ctx);
    let convIds = null;
    if (provider && provider !== "all") {
      const { data: matches, error: mErr } = await supabase.from("messages").select("conversation_id").eq("provider", provider).order("created_at", { ascending: false }).limit(500);
      if (mErr) return { content: [{ type: "text", text: mErr.message }], isError: true };
      convIds = [...new Set((matches ?? []).map((m) => m.conversation_id))];
      if (convIds.length === 0) {
        const result2 = { count: 0, conversations: [] };
        return { content: [{ type: "text", text: JSON.stringify(result2, null, 2) }], structuredContent: result2 };
      }
    }
    let query = supabase.from("conversations").select(
      "id, contact_id, last_message, last_message_at, last_inbound_at, last_outbound_at, unread_count, status, contacts(name, phone_normalized)"
    ).order("last_message_at", { ascending: false, nullsFirst: false }).limit(limit ?? 25);
    if (unread_only) query = query.gt("unread_count", 0);
    if (convIds) query = query.in("id", convIds);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const result = { count: data?.length ?? 0, conversations: data ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/get-conversation-thread.ts
import { defineTool as defineTool25 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z21 } from "npm:zod@^3.25.76";
var get_conversation_thread_default = defineTool25({
  name: "get_conversation_thread",
  title: "Get a conversation's full message thread",
  description: "Full message history for one conversation (oldest first), each message tagged with its channel (twilio/maytapi) and whether it was inbound or outbound. Also returns the most recent automated-reply events for this conversation, so you can see whether the whatsapp-auto-reply bot already answered before drafting a manual reply.",
  inputSchema: {
    conversation_id: z21.string().uuid().describe("conversations.id \u2014 get this from list_conversations."),
    limit: z21.number().int().min(1).max(200).optional().describe("Max messages (default 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ conversation_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    const supabase = supabaseForUser(ctx);
    const { data: conv, error: convErr } = await supabase.from("conversations").select("id, contact_id, status, unread_count, contacts(name, phone_normalized)").eq("id", conversation_id).maybeSingle();
    if (convErr) return { content: [{ type: "text", text: convErr.message }], isError: true };
    if (!conv) return { content: [{ type: "text", text: "Conversation not found" }], isError: true };
    const { data: messages, error: msgErr } = await supabase.from("messages").select("id, content, is_outbound, provider, status, status_raw, created_at, provider_message_id").eq("conversation_id", conversation_id).order("created_at", { ascending: true }).limit(limit ?? 100);
    if (msgErr) return { content: [{ type: "text", text: msgErr.message }], isError: true };
    const { data: autoReplyEvents } = await supabase.from("auto_reply_events").select("action_taken, reason, template_used, knowledge_found, created_at").eq("conversation_id", conversation_id).order("created_at", { ascending: false }).limit(5);
    const result = {
      conversation: conv,
      messages: messages ?? [],
      recent_auto_reply_events: autoReplyEvents ?? []
    };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/reply-to-conversation.ts
import { defineTool as defineTool26 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z22 } from "npm:zod@^3.25.76";
var reply_to_conversation_default = defineTool26({
  name: "reply_to_conversation",
  title: "Reply in a conversation",
  description: "Send a reply into an existing conversation via the existing send-message function, which auto-routes to Twilio or Maytapi based on which channel the contact last messaged in. Enforces the same 24-hour customer-service-window check and price/link safety validator as manual replies sent from the app \u2014 refuses rather than sending unsafe or out-of-window content.",
  inputSchema: {
    conversation_id: z22.string().uuid().describe("conversations.id \u2014 get this from list_conversations or get_conversation_thread."),
    message_body: z22.string().min(1).max(4e3).describe("The exact final text to send. No templating is applied.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
  handler: async ({ conversation_id, message_body }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.functions.invoke("send-message", {
      body: { conversation_id, content: message_body }
    });
    if (error) {
      return {
        content: [{ type: "text", text: `send-message invocation failed: ${error.message}` }],
        structuredContent: { sent: false, reason: "invoke_error" },
        isError: true
      };
    }
    if (!data?.ok) {
      return {
        content: [
          {
            type: "text",
            text: `Refused: [${data?.code}] ${data?.message}${data?.hint ? " \u2014 " + data.hint : ""}`
          }
        ],
        structuredContent: { sent: false, ...data },
        isError: true
      };
    }
    const result = { sent: true, ...data.message };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "nqyyvqcmcyggvlcswkio";
var mcp_default = defineMcp({
  name: "get-well-hub",
  title: "Get Well Hub",
  version: "1.1.0",
  instructions: "Tools for Get Well Hub, a WhatsApp CRM. Call get_dispatch_policy before scheduling any WhatsApp campaign: the dispatcher sends 1 group post per 5-minute tick, so an 11-group wave takes ~55 minutes to clear and final waves must start 60-70 minutes before any time-sensitive event. Posts are queued with status 'pending'. All contact tools act as the signed-in user under row-level security. For 1:1 inbox work across Twilio and Maytapi, use list_conversations \u2192 get_conversation_thread (check recent_auto_reply_events before replying) \u2192 reply_to_conversation.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    get_dispatch_policy_default,
    get_dispatcher_health_default,
    get_maytapi_status_default,
    set_maytapi_cap_default,
    set_maytapi_freeze_default,
    queue_group_post_default,
    get_prospector_status_default,
    list_contacts_default,
    get_contact_default,
    update_contact_default,
    add_contact_note_default,
    create_plan_task_default,
    create_plan_meeting_default,
    create_plan_reminder_default,
    send_whatsapp_message_default,
    list_plan_tasks_default,
    complete_plan_task_default,
    delete_plan_task_default,
    list_plan_reminders_default,
    complete_plan_reminder_default,
    delete_plan_reminder_default,
    list_plan_meetings_default,
    delete_plan_meeting_default,
    list_conversations_default,
    get_conversation_thread_default,
    reply_to_conversation_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
